language: swift
script:
  - set -o pipefail
  - xcodebuild $XCODE_ACTION
      -scheme "$TRAVIS_XCODE_SCHEME"
      -sdk "$XCODE_SDK"
      -destination "$XCODE_DESTINATION"
matrix:
  include:
    - xcode_scheme: "Spine-macOS"
      osx_image: xcode9.3
      env:
        - XCODE_ACTION=test
        - XCODE_SDK=macosx
        - XCODE_DESTINATION="arch=x86_64"
    - xcode_scheme: "Spine-iOS"
      osx_image: xcode9.3
      env:
        - XCODE_ACTION=test
        - XCODE_SDK=iphonesimulator
        - XCODE_DESTINATION="name=iPhone 7"
    - xcode_scheme: "Spine-tvOS"
      osx_image: xcode9.3
      env:
        - XCODE_ACTION=test
        - XCODE_SDK=appletvsimulator
        - XCODE_DESTINATION="name=Apple TV 4K"
    - xcode_scheme: "Spine-watchOS"
      osx_image: xcode9.3
      env:
        - XCODE_ACTION=build
        - XCODE_SDK=watchsimulator
        - XCODE_DESTINATION="name=Apple Watch - 38mm"
